# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "990d931560e5357246edbb91fd0b8d4d"
application_url = "https://fulfillment-cleanup-app.onrender.com"
embedded = true
name = "fulfillment-cleanup-app"

[access_scopes]
scopes = "read_orders,read_all_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders"

[auth]
redirect_urls = [ "https://fulfillment-cleanup-app.onrender.com/auth/callback" ]

[webhooks]
api_version = "2026-10"
[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "/webhooks/orders/create"


[build]
automatically_update_urls_on_dev = false
